api_login_check:
    path: /api/login_check
    controller: App\Controller\AuthController::getTokenUser
    methods: POST

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
